# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vent_memoriaSD.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_memoriaSD(object):
    def setupUi(self, memoriaSD):
        memoriaSD.setObjectName("memoriaSD")
        memoriaSD.resize(951, 510)
        memoriaSD.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gridLayout = QtWidgets.QGridLayout(memoriaSD)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(memoriaSD)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 931, 490))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 8, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 10, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 9, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 9, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 10, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 8, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 9, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 10, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 8, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 9, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 1, 0, 2, 3)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 10, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 8, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 9, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButtonPix0 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.pushButtonPix0.setText("")
        self.pushButtonPix0.setObjectName("pushButtonPix0")
        self.pushButtonPix1 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1.setGeometry(QtCore.QRect(20, 50, 31, 31))
        self.pushButtonPix1.setText("")
        self.pushButtonPix1.setObjectName("pushButtonPix1")
        self.pushButtonPix3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3.setGeometry(QtCore.QRect(20, 110, 31, 31))
        self.pushButtonPix3.setText("")
        self.pushButtonPix3.setObjectName("pushButtonPix3")
        self.pushButtonPix2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.pushButtonPix2.setText("")
        self.pushButtonPix2.setObjectName("pushButtonPix2")
        self.pushButtonPix5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5.setGeometry(QtCore.QRect(20, 170, 31, 31))
        self.pushButtonPix5.setText("")
        self.pushButtonPix5.setObjectName("pushButtonPix5")
        self.pushButtonPix4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4.setGeometry(QtCore.QRect(20, 140, 31, 31))
        self.pushButtonPix4.setText("")
        self.pushButtonPix4.setObjectName("pushButtonPix4")
        self.pushButtonPix7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7.setGeometry(QtCore.QRect(20, 230, 31, 31))
        self.pushButtonPix7.setText("")
        self.pushButtonPix7.setObjectName("pushButtonPix7")
        self.pushButtonPix6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6.setGeometry(QtCore.QRect(20, 200, 31, 31))
        self.pushButtonPix6.setText("")
        self.pushButtonPix6.setObjectName("pushButtonPix6")
        self.pushButtonPix6_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_2.setGeometry(QtCore.QRect(50, 200, 31, 31))
        self.pushButtonPix6_2.setText("")
        self.pushButtonPix6_2.setObjectName("pushButtonPix6_2")
        self.pushButtonPix4_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_2.setGeometry(QtCore.QRect(50, 140, 31, 31))
        self.pushButtonPix4_2.setText("")
        self.pushButtonPix4_2.setObjectName("pushButtonPix4_2")
        self.pushButtonPix5_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_2.setGeometry(QtCore.QRect(50, 170, 31, 31))
        self.pushButtonPix5_2.setText("")
        self.pushButtonPix5_2.setObjectName("pushButtonPix5_2")
        self.pushButtonPix1_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_2.setGeometry(QtCore.QRect(50, 50, 31, 31))
        self.pushButtonPix1_2.setText("")
        self.pushButtonPix1_2.setObjectName("pushButtonPix1_2")
        self.pushButtonPix2_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_2.setGeometry(QtCore.QRect(50, 80, 31, 31))
        self.pushButtonPix2_2.setText("")
        self.pushButtonPix2_2.setObjectName("pushButtonPix2_2")
        self.pushButtonPix7_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_2.setGeometry(QtCore.QRect(50, 230, 31, 31))
        self.pushButtonPix7_2.setText("")
        self.pushButtonPix7_2.setObjectName("pushButtonPix7_2")
        self.pushButtonPix0_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_2.setGeometry(QtCore.QRect(50, 20, 31, 31))
        self.pushButtonPix0_2.setText("")
        self.pushButtonPix0_2.setObjectName("pushButtonPix0_2")
        self.pushButtonPix3_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_2.setGeometry(QtCore.QRect(50, 110, 31, 31))
        self.pushButtonPix3_2.setText("")
        self.pushButtonPix3_2.setObjectName("pushButtonPix3_2")
        self.pushButtonPix6_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_3.setGeometry(QtCore.QRect(80, 200, 31, 31))
        self.pushButtonPix6_3.setText("")
        self.pushButtonPix6_3.setObjectName("pushButtonPix6_3")
        self.pushButtonPix4_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_3.setGeometry(QtCore.QRect(80, 140, 31, 31))
        self.pushButtonPix4_3.setText("")
        self.pushButtonPix4_3.setObjectName("pushButtonPix4_3")
        self.pushButtonPix5_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_3.setGeometry(QtCore.QRect(80, 170, 31, 31))
        self.pushButtonPix5_3.setText("")
        self.pushButtonPix5_3.setObjectName("pushButtonPix5_3")
        self.pushButtonPix1_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_3.setGeometry(QtCore.QRect(80, 50, 31, 31))
        self.pushButtonPix1_3.setText("")
        self.pushButtonPix1_3.setObjectName("pushButtonPix1_3")
        self.pushButtonPix2_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_3.setGeometry(QtCore.QRect(80, 80, 31, 31))
        self.pushButtonPix2_3.setText("")
        self.pushButtonPix2_3.setObjectName("pushButtonPix2_3")
        self.pushButtonPix7_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_3.setGeometry(QtCore.QRect(80, 230, 31, 31))
        self.pushButtonPix7_3.setText("")
        self.pushButtonPix7_3.setObjectName("pushButtonPix7_3")
        self.pushButtonPix0_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_3.setGeometry(QtCore.QRect(80, 20, 31, 31))
        self.pushButtonPix0_3.setText("")
        self.pushButtonPix0_3.setObjectName("pushButtonPix0_3")
        self.pushButtonPix3_3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_3.setGeometry(QtCore.QRect(80, 110, 31, 31))
        self.pushButtonPix3_3.setText("")
        self.pushButtonPix3_3.setObjectName("pushButtonPix3_3")
        self.pushButtonPix6_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_4.setGeometry(QtCore.QRect(110, 200, 31, 31))
        self.pushButtonPix6_4.setText("")
        self.pushButtonPix6_4.setObjectName("pushButtonPix6_4")
        self.pushButtonPix4_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_4.setGeometry(QtCore.QRect(110, 140, 31, 31))
        self.pushButtonPix4_4.setText("")
        self.pushButtonPix4_4.setObjectName("pushButtonPix4_4")
        self.pushButtonPix5_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_4.setGeometry(QtCore.QRect(110, 170, 31, 31))
        self.pushButtonPix5_4.setText("")
        self.pushButtonPix5_4.setObjectName("pushButtonPix5_4")
        self.pushButtonPix1_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_4.setGeometry(QtCore.QRect(110, 50, 31, 31))
        self.pushButtonPix1_4.setText("")
        self.pushButtonPix1_4.setObjectName("pushButtonPix1_4")
        self.pushButtonPix2_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_4.setGeometry(QtCore.QRect(110, 80, 31, 31))
        self.pushButtonPix2_4.setText("")
        self.pushButtonPix2_4.setObjectName("pushButtonPix2_4")
        self.pushButtonPix7_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_4.setGeometry(QtCore.QRect(110, 230, 31, 31))
        self.pushButtonPix7_4.setText("")
        self.pushButtonPix7_4.setObjectName("pushButtonPix7_4")
        self.pushButtonPix0_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_4.setGeometry(QtCore.QRect(110, 20, 31, 31))
        self.pushButtonPix0_4.setText("")
        self.pushButtonPix0_4.setObjectName("pushButtonPix0_4")
        self.pushButtonPix3_4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_4.setGeometry(QtCore.QRect(110, 110, 31, 31))
        self.pushButtonPix3_4.setText("")
        self.pushButtonPix3_4.setObjectName("pushButtonPix3_4")
        self.pushButtonPix6_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_5.setGeometry(QtCore.QRect(140, 200, 31, 31))
        self.pushButtonPix6_5.setText("")
        self.pushButtonPix6_5.setObjectName("pushButtonPix6_5")
        self.pushButtonPix4_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_5.setGeometry(QtCore.QRect(140, 140, 31, 31))
        self.pushButtonPix4_5.setText("")
        self.pushButtonPix4_5.setObjectName("pushButtonPix4_5")
        self.pushButtonPix5_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_5.setGeometry(QtCore.QRect(140, 170, 31, 31))
        self.pushButtonPix5_5.setText("")
        self.pushButtonPix5_5.setObjectName("pushButtonPix5_5")
        self.pushButtonPix1_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_5.setGeometry(QtCore.QRect(140, 50, 31, 31))
        self.pushButtonPix1_5.setText("")
        self.pushButtonPix1_5.setObjectName("pushButtonPix1_5")
        self.pushButtonPix2_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_5.setGeometry(QtCore.QRect(140, 80, 31, 31))
        self.pushButtonPix2_5.setText("")
        self.pushButtonPix2_5.setObjectName("pushButtonPix2_5")
        self.pushButtonPix7_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_5.setGeometry(QtCore.QRect(140, 230, 31, 31))
        self.pushButtonPix7_5.setText("")
        self.pushButtonPix7_5.setObjectName("pushButtonPix7_5")
        self.pushButtonPix0_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_5.setGeometry(QtCore.QRect(140, 20, 31, 31))
        self.pushButtonPix0_5.setText("")
        self.pushButtonPix0_5.setObjectName("pushButtonPix0_5")
        self.pushButtonPix3_5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_5.setGeometry(QtCore.QRect(140, 110, 31, 31))
        self.pushButtonPix3_5.setText("")
        self.pushButtonPix3_5.setObjectName("pushButtonPix3_5")
        self.pushButtonPix6_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_6.setGeometry(QtCore.QRect(170, 200, 31, 31))
        self.pushButtonPix6_6.setText("")
        self.pushButtonPix6_6.setObjectName("pushButtonPix6_6")
        self.pushButtonPix4_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_6.setGeometry(QtCore.QRect(170, 140, 31, 31))
        self.pushButtonPix4_6.setText("")
        self.pushButtonPix4_6.setObjectName("pushButtonPix4_6")
        self.pushButtonPix5_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_6.setGeometry(QtCore.QRect(170, 170, 31, 31))
        self.pushButtonPix5_6.setText("")
        self.pushButtonPix5_6.setObjectName("pushButtonPix5_6")
        self.pushButtonPix1_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_6.setGeometry(QtCore.QRect(170, 50, 31, 31))
        self.pushButtonPix1_6.setText("")
        self.pushButtonPix1_6.setObjectName("pushButtonPix1_6")
        self.pushButtonPix2_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_6.setGeometry(QtCore.QRect(170, 80, 31, 31))
        self.pushButtonPix2_6.setText("")
        self.pushButtonPix2_6.setObjectName("pushButtonPix2_6")
        self.pushButtonPix7_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_6.setGeometry(QtCore.QRect(170, 230, 31, 31))
        self.pushButtonPix7_6.setText("")
        self.pushButtonPix7_6.setObjectName("pushButtonPix7_6")
        self.pushButtonPix0_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_6.setGeometry(QtCore.QRect(170, 20, 31, 31))
        self.pushButtonPix0_6.setText("")
        self.pushButtonPix0_6.setObjectName("pushButtonPix0_6")
        self.pushButtonPix3_6 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_6.setGeometry(QtCore.QRect(170, 110, 31, 31))
        self.pushButtonPix3_6.setText("")
        self.pushButtonPix3_6.setObjectName("pushButtonPix3_6")
        self.pushButtonPix6_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_7.setGeometry(QtCore.QRect(200, 200, 31, 31))
        self.pushButtonPix6_7.setText("")
        self.pushButtonPix6_7.setObjectName("pushButtonPix6_7")
        self.pushButtonPix4_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_7.setGeometry(QtCore.QRect(200, 140, 31, 31))
        self.pushButtonPix4_7.setText("")
        self.pushButtonPix4_7.setObjectName("pushButtonPix4_7")
        self.pushButtonPix5_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_7.setGeometry(QtCore.QRect(200, 170, 31, 31))
        self.pushButtonPix5_7.setText("")
        self.pushButtonPix5_7.setObjectName("pushButtonPix5_7")
        self.pushButtonPix1_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_7.setGeometry(QtCore.QRect(200, 50, 31, 31))
        self.pushButtonPix1_7.setText("")
        self.pushButtonPix1_7.setObjectName("pushButtonPix1_7")
        self.pushButtonPix2_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_7.setGeometry(QtCore.QRect(200, 80, 31, 31))
        self.pushButtonPix2_7.setText("")
        self.pushButtonPix2_7.setObjectName("pushButtonPix2_7")
        self.pushButtonPix7_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_7.setGeometry(QtCore.QRect(200, 230, 31, 31))
        self.pushButtonPix7_7.setText("")
        self.pushButtonPix7_7.setObjectName("pushButtonPix7_7")
        self.pushButtonPix0_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_7.setGeometry(QtCore.QRect(200, 20, 31, 31))
        self.pushButtonPix0_7.setText("")
        self.pushButtonPix0_7.setObjectName("pushButtonPix0_7")
        self.pushButtonPix3_7 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_7.setGeometry(QtCore.QRect(200, 110, 31, 31))
        self.pushButtonPix3_7.setText("")
        self.pushButtonPix3_7.setObjectName("pushButtonPix3_7")
        self.pushButtonPix6_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_8.setGeometry(QtCore.QRect(230, 200, 31, 31))
        self.pushButtonPix6_8.setText("")
        self.pushButtonPix6_8.setObjectName("pushButtonPix6_8")
        self.pushButtonPix4_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_8.setGeometry(QtCore.QRect(230, 140, 31, 31))
        self.pushButtonPix4_8.setText("")
        self.pushButtonPix4_8.setObjectName("pushButtonPix4_8")
        self.pushButtonPix5_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_8.setGeometry(QtCore.QRect(230, 170, 31, 31))
        self.pushButtonPix5_8.setText("")
        self.pushButtonPix5_8.setObjectName("pushButtonPix5_8")
        self.pushButtonPix1_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_8.setGeometry(QtCore.QRect(230, 50, 31, 31))
        self.pushButtonPix1_8.setText("")
        self.pushButtonPix1_8.setObjectName("pushButtonPix1_8")
        self.pushButtonPix2_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_8.setGeometry(QtCore.QRect(230, 80, 31, 31))
        self.pushButtonPix2_8.setText("")
        self.pushButtonPix2_8.setObjectName("pushButtonPix2_8")
        self.pushButtonPix7_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_8.setGeometry(QtCore.QRect(230, 230, 31, 31))
        self.pushButtonPix7_8.setText("")
        self.pushButtonPix7_8.setObjectName("pushButtonPix7_8")
        self.pushButtonPix0_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_8.setGeometry(QtCore.QRect(230, 20, 31, 31))
        self.pushButtonPix0_8.setText("")
        self.pushButtonPix0_8.setObjectName("pushButtonPix0_8")
        self.pushButtonPix3_8 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_8.setGeometry(QtCore.QRect(230, 110, 31, 31))
        self.pushButtonPix3_8.setText("")
        self.pushButtonPix3_8.setObjectName("pushButtonPix3_8")
        self.pushButtonPix6_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_9.setGeometry(QtCore.QRect(260, 200, 31, 31))
        self.pushButtonPix6_9.setText("")
        self.pushButtonPix6_9.setObjectName("pushButtonPix6_9")
        self.pushButtonPix4_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_9.setGeometry(QtCore.QRect(260, 140, 31, 31))
        self.pushButtonPix4_9.setText("")
        self.pushButtonPix4_9.setObjectName("pushButtonPix4_9")
        self.pushButtonPix5_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_9.setGeometry(QtCore.QRect(260, 170, 31, 31))
        self.pushButtonPix5_9.setText("")
        self.pushButtonPix5_9.setObjectName("pushButtonPix5_9")
        self.pushButtonPix1_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_9.setGeometry(QtCore.QRect(260, 50, 31, 31))
        self.pushButtonPix1_9.setText("")
        self.pushButtonPix1_9.setObjectName("pushButtonPix1_9")
        self.pushButtonPix2_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_9.setGeometry(QtCore.QRect(260, 80, 31, 31))
        self.pushButtonPix2_9.setText("")
        self.pushButtonPix2_9.setObjectName("pushButtonPix2_9")
        self.pushButtonPix7_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_9.setGeometry(QtCore.QRect(260, 230, 31, 31))
        self.pushButtonPix7_9.setText("")
        self.pushButtonPix7_9.setObjectName("pushButtonPix7_9")
        self.pushButtonPix0_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_9.setGeometry(QtCore.QRect(260, 20, 31, 31))
        self.pushButtonPix0_9.setText("")
        self.pushButtonPix0_9.setObjectName("pushButtonPix0_9")
        self.pushButtonPix3_9 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_9.setGeometry(QtCore.QRect(260, 110, 31, 31))
        self.pushButtonPix3_9.setText("")
        self.pushButtonPix3_9.setObjectName("pushButtonPix3_9")
        self.pushButtonPix6_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_10.setGeometry(QtCore.QRect(290, 200, 31, 31))
        self.pushButtonPix6_10.setText("")
        self.pushButtonPix6_10.setObjectName("pushButtonPix6_10")
        self.pushButtonPix4_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_10.setGeometry(QtCore.QRect(290, 140, 31, 31))
        self.pushButtonPix4_10.setText("")
        self.pushButtonPix4_10.setObjectName("pushButtonPix4_10")
        self.pushButtonPix5_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_10.setGeometry(QtCore.QRect(290, 170, 31, 31))
        self.pushButtonPix5_10.setText("")
        self.pushButtonPix5_10.setObjectName("pushButtonPix5_10")
        self.pushButtonPix1_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_10.setGeometry(QtCore.QRect(290, 50, 31, 31))
        self.pushButtonPix1_10.setText("")
        self.pushButtonPix1_10.setObjectName("pushButtonPix1_10")
        self.pushButtonPix2_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_10.setGeometry(QtCore.QRect(290, 80, 31, 31))
        self.pushButtonPix2_10.setText("")
        self.pushButtonPix2_10.setObjectName("pushButtonPix2_10")
        self.pushButtonPix7_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_10.setGeometry(QtCore.QRect(290, 230, 31, 31))
        self.pushButtonPix7_10.setText("")
        self.pushButtonPix7_10.setObjectName("pushButtonPix7_10")
        self.pushButtonPix0_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_10.setGeometry(QtCore.QRect(290, 20, 31, 31))
        self.pushButtonPix0_10.setText("")
        self.pushButtonPix0_10.setObjectName("pushButtonPix0_10")
        self.pushButtonPix3_10 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_10.setGeometry(QtCore.QRect(290, 110, 31, 31))
        self.pushButtonPix3_10.setText("")
        self.pushButtonPix3_10.setObjectName("pushButtonPix3_10")
        self.pushButtonPix6_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_11.setGeometry(QtCore.QRect(320, 200, 31, 31))
        self.pushButtonPix6_11.setText("")
        self.pushButtonPix6_11.setObjectName("pushButtonPix6_11")
        self.pushButtonPix4_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_11.setGeometry(QtCore.QRect(320, 140, 31, 31))
        self.pushButtonPix4_11.setText("")
        self.pushButtonPix4_11.setObjectName("pushButtonPix4_11")
        self.pushButtonPix5_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_11.setGeometry(QtCore.QRect(320, 170, 31, 31))
        self.pushButtonPix5_11.setText("")
        self.pushButtonPix5_11.setObjectName("pushButtonPix5_11")
        self.pushButtonPix1_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_11.setGeometry(QtCore.QRect(320, 50, 31, 31))
        self.pushButtonPix1_11.setText("")
        self.pushButtonPix1_11.setObjectName("pushButtonPix1_11")
        self.pushButtonPix2_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_11.setGeometry(QtCore.QRect(320, 80, 31, 31))
        self.pushButtonPix2_11.setText("")
        self.pushButtonPix2_11.setObjectName("pushButtonPix2_11")
        self.pushButtonPix7_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_11.setGeometry(QtCore.QRect(320, 230, 31, 31))
        self.pushButtonPix7_11.setText("")
        self.pushButtonPix7_11.setObjectName("pushButtonPix7_11")
        self.pushButtonPix0_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_11.setGeometry(QtCore.QRect(320, 20, 31, 31))
        self.pushButtonPix0_11.setText("")
        self.pushButtonPix0_11.setObjectName("pushButtonPix0_11")
        self.pushButtonPix3_11 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_11.setGeometry(QtCore.QRect(320, 110, 31, 31))
        self.pushButtonPix3_11.setText("")
        self.pushButtonPix3_11.setObjectName("pushButtonPix3_11")
        self.pushButtonPix6_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix6_12.setGeometry(QtCore.QRect(350, 200, 31, 31))
        self.pushButtonPix6_12.setText("")
        self.pushButtonPix6_12.setObjectName("pushButtonPix6_12")
        self.pushButtonPix4_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix4_12.setGeometry(QtCore.QRect(350, 140, 31, 31))
        self.pushButtonPix4_12.setText("")
        self.pushButtonPix4_12.setObjectName("pushButtonPix4_12")
        self.pushButtonPix5_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix5_12.setGeometry(QtCore.QRect(350, 170, 31, 31))
        self.pushButtonPix5_12.setText("")
        self.pushButtonPix5_12.setObjectName("pushButtonPix5_12")
        self.pushButtonPix1_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix1_12.setGeometry(QtCore.QRect(350, 50, 31, 31))
        self.pushButtonPix1_12.setText("")
        self.pushButtonPix1_12.setObjectName("pushButtonPix1_12")
        self.pushButtonPix2_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix2_12.setGeometry(QtCore.QRect(350, 80, 31, 31))
        self.pushButtonPix2_12.setText("")
        self.pushButtonPix2_12.setObjectName("pushButtonPix2_12")
        self.pushButtonPix7_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix7_12.setGeometry(QtCore.QRect(350, 230, 31, 31))
        self.pushButtonPix7_12.setText("")
        self.pushButtonPix7_12.setObjectName("pushButtonPix7_12")
        self.pushButtonPix0_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix0_12.setGeometry(QtCore.QRect(350, 20, 31, 31))
        self.pushButtonPix0_12.setText("")
        self.pushButtonPix0_12.setObjectName("pushButtonPix0_12")
        self.pushButtonPix3_12 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPix3_12.setGeometry(QtCore.QRect(350, 110, 31, 31))
        self.pushButtonPix3_12.setText("")
        self.pushButtonPix3_12.setObjectName("pushButtonPix3_12")
        self.labelPix0 = QtWidgets.QLabel(self.frame)
        self.labelPix0.setGeometry(QtCore.QRect(20, 270, 31, 20))
        self.labelPix0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix0.setObjectName("labelPix0")
        self.labelPix1 = QtWidgets.QLabel(self.frame)
        self.labelPix1.setGeometry(QtCore.QRect(50, 270, 31, 20))
        self.labelPix1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix1.setObjectName("labelPix1")
        self.labelPix2 = QtWidgets.QLabel(self.frame)
        self.labelPix2.setGeometry(QtCore.QRect(80, 270, 31, 20))
        self.labelPix2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix2.setObjectName("labelPix2")
        self.labelPix3 = QtWidgets.QLabel(self.frame)
        self.labelPix3.setGeometry(QtCore.QRect(110, 270, 31, 20))
        self.labelPix3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix3.setObjectName("labelPix3")
        self.labelPix4 = QtWidgets.QLabel(self.frame)
        self.labelPix4.setGeometry(QtCore.QRect(140, 270, 31, 20))
        self.labelPix4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix4.setObjectName("labelPix4")
        self.labelPix5 = QtWidgets.QLabel(self.frame)
        self.labelPix5.setGeometry(QtCore.QRect(170, 270, 31, 20))
        self.labelPix5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix5.setObjectName("labelPix5")
        self.labelPix6 = QtWidgets.QLabel(self.frame)
        self.labelPix6.setGeometry(QtCore.QRect(200, 270, 31, 20))
        self.labelPix6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix6.setObjectName("labelPix6")
        self.labelPix7 = QtWidgets.QLabel(self.frame)
        self.labelPix7.setGeometry(QtCore.QRect(230, 270, 31, 20))
        self.labelPix7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix7.setObjectName("labelPix7")
        self.labelPix8 = QtWidgets.QLabel(self.frame)
        self.labelPix8.setGeometry(QtCore.QRect(260, 270, 31, 20))
        self.labelPix8.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix8.setObjectName("labelPix8")
        self.labelPix9 = QtWidgets.QLabel(self.frame)
        self.labelPix9.setGeometry(QtCore.QRect(290, 270, 31, 20))
        self.labelPix9.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix9.setObjectName("labelPix9")
        self.labelPix10 = QtWidgets.QLabel(self.frame)
        self.labelPix10.setGeometry(QtCore.QRect(320, 270, 31, 20))
        self.labelPix10.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix10.setObjectName("labelPix10")
        self.labelPix11 = QtWidgets.QLabel(self.frame)
        self.labelPix11.setGeometry(QtCore.QRect(350, 270, 31, 20))
        self.labelPix11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPix11.setObjectName("labelPix11")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 310, 90, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 310, 90, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 310, 141, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.frame, 1, 3, 2, 3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 8, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 9, 5, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 10, 4, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 3, 1, 1)

        self.retranslateUi(memoriaSD)
        QtCore.QMetaObject.connectSlotsByName(memoriaSD)

    def retranslateUi(self, memoriaSD):
        _translate = QtCore.QCoreApplication.translate
        memoriaSD.setWindowTitle(_translate("memoriaSD", "Lector de Memoria SD"))
        self.label.setText(_translate("memoriaSD", "Dirección"))
        self.label_3.setText(_translate("memoriaSD", "Valor"))
        self.pushButton_3.setText(_translate("memoriaSD", "Leer Dirección"))
        self.lineEdit_4.setText(_translate("memoriaSD", "0"))
        self.pushButton_2.setText(_translate("memoriaSD", "Leer Bloques"))
        self.lineEdit.setText(_translate("memoriaSD", "0"))
        self.lineEdit_5.setText(_translate("memoriaSD", "0"))
        self.pushButton_4.setText(_translate("memoriaSD", "Escribir Dirección"))
        self.pushButton_5.setText(_translate("memoriaSD", "Imagen -> microSD"))
        self.label_5.setText(_translate("memoriaSD", "Dirección Final"))
        self.pushButton.setText(_translate("memoriaSD", "Inicializar Memoria"))
        self.label_4.setText(_translate("memoriaSD", "Dirección Inicial"))
        self.labelPix0.setText(_translate("memoriaSD", "0"))
        self.labelPix1.setText(_translate("memoriaSD", "0"))
        self.labelPix2.setText(_translate("memoriaSD", "0"))
        self.labelPix3.setText(_translate("memoriaSD", "0"))
        self.labelPix4.setText(_translate("memoriaSD", "0"))
        self.labelPix5.setText(_translate("memoriaSD", "0"))
        self.labelPix6.setText(_translate("memoriaSD", "0"))
        self.labelPix7.setText(_translate("memoriaSD", "0"))
        self.labelPix8.setText(_translate("memoriaSD", "0"))
        self.labelPix9.setText(_translate("memoriaSD", "0"))
        self.labelPix10.setText(_translate("memoriaSD", "0"))
        self.labelPix11.setText(_translate("memoriaSD", "0"))
        self.pushButton_7.setText(_translate("memoriaSD", "Anterior"))
        self.pushButton_8.setText(_translate("memoriaSD", "Siguiente"))
        self.label_2.setText(_translate("memoriaSD", "Dirección de fuente"))
        self.pushButton_6.setText(_translate("memoriaSD", "Leer Fuentes"))
        self.pushButton_9.setText(_translate("memoriaSD", "Subir Fuentes"))

