# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vent_memoriaSD.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_memoriaSD(object):
    def setupUi(self, memoriaSD):
        memoriaSD.setObjectName("memoriaSD")
        memoriaSD.resize(1181, 764)
        memoriaSD.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gridLayout = QtWidgets.QGridLayout(memoriaSD)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(memoriaSD)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1161, 744))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 561, 481))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 500, 141, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(170, 500, 151, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 640, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 640, 171, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(320, 500, 131, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(460, 500, 81, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 680, 121, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 680, 171, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 560, 151, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 560, 141, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 560, 141, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 637, 141, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_4.raise_()
        self.lineEdit_4.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_4.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 2, 2)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(280, 90, 121, 30))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 90, 140, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 210, 121, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(408, 210, 141, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 240, 320))
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(380, 40, 171, 30))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(280, 40, 81, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(408, 150, 141, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(280, 150, 121, 30))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox.raise_()
        self.pushButton_5.raise_()
        self.comboBox_2.raise_()
        self.pushButton_6.raise_()
        self.lineEdit_3.raise_()
        self.graphicsView.raise_()
        self.comboBox_3.raise_()
        self.label_6.raise_()
        self.pushButton_7.raise_()
        self.comboBox_4.raise_()
        self.gridLayout_3.addWidget(self.frame, 1, 3, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.frame_3, 2, 3, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 1, 1)

        self.retranslateUi(memoriaSD)
        QtCore.QMetaObject.connectSlotsByName(memoriaSD)

    def retranslateUi(self, memoriaSD):
        _translate = QtCore.QCoreApplication.translate
        memoriaSD.setWindowTitle(_translate("memoriaSD", "Lector de Memoria SD"))
        self.label.setText(_translate("memoriaSD", "Dirección [decimal]"))
        self.lineEdit.setText(_translate("memoriaSD", "0"))
        self.label_4.setText(_translate("memoriaSD", "Dirección Inicial"))
        self.lineEdit_4.setText(_translate("memoriaSD", "0"))
        self.label_3.setText(_translate("memoriaSD", "Valor [decimal]"))
        self.label_5.setText(_translate("memoriaSD", "Dirección Final"))
        self.lineEdit_5.setText(_translate("memoriaSD", "0"))
        self.pushButton.setText(_translate("memoriaSD", "Inicializar Memoria"))
        self.pushButton_3.setText(_translate("memoriaSD", "Leer Dirección"))
        self.pushButton_4.setText(_translate("memoriaSD", "Escribir Dirección"))
        self.pushButton_2.setText(_translate("memoriaSD", "Leer Bloques"))
        self.pushButton_5.setText(_translate("memoriaSD", "Imagen -> microSD"))
        self.pushButton_6.setText(_translate("memoriaSD", "Fuentes -> microSD"))
        self.label_6.setText(_translate("memoriaSD", "Dirección "))
        self.pushButton_7.setText(_translate("memoriaSD", "Iconos -> microSD"))
        self.label_2.setText(_translate("memoriaSD", "Editor de Imagen"))

