# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vent_perceptron.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_perceptron(object):
    def setupUi(self, perceptron):
        perceptron.setObjectName("perceptron")
        perceptron.resize(1229, 522)
        perceptron.setStyleSheet("background-color: rgb(252, 255, 224);")
        self.label_6 = QtWidgets.QLabel(perceptron)
        self.label_6.setGeometry(QtCore.QRect(10, 498, 1211, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalSlider_3 = QtWidgets.QSlider(perceptron)
        self.verticalSlider_3.setGeometry(QtCore.QRect(340, 290, 31, 149))
        self.verticalSlider_3.setMaximum(255)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.label_2 = QtWidgets.QLabel(perceptron)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 371, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalSlider_2 = QtWidgets.QSlider(perceptron)
        self.verticalSlider_2.setGeometry(QtCore.QRect(210, 290, 31, 149))
        self.verticalSlider_2.setMaximum(255)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.label = QtWidgets.QLabel(perceptron)
        self.label.setGeometry(QtCore.QRect(30, 450, 601, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(perceptron)
        self.label_3.setGeometry(QtCore.QRect(60, 250, 71, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(perceptron)
        self.pushButton.setGeometry(QtCore.QRect(590, 270, 151, 51))
        self.pushButton.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(perceptron)
        self.label_5.setGeometry(QtCore.QRect(325, 250, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(perceptron)
        self.label_4.setGeometry(QtCore.QRect(185, 250, 81, 31))
        self.label_4.setObjectName("label_4")
        self.verticalSlider = QtWidgets.QSlider(perceptron)
        self.verticalSlider.setGeometry(QtCore.QRect(80, 290, 16, 149))
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_7 = QtWidgets.QLabel(perceptron)
        self.label_7.setGeometry(QtCore.QRect(450, 60, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(perceptron)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 390, 151, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(perceptron)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 330, 151, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(perceptron)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 390, 151, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser = QtWidgets.QTextBrowser(perceptron)
        self.textBrowser.setGeometry(QtCore.QRect(760, 400, 451, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.label_8 = QtWidgets.QLabel(perceptron)
        self.label_8.setGeometry(QtCore.QRect(240, 60, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(perceptron)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(perceptron)
        self.label_10.setGeometry(QtCore.QRect(80, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(perceptron)
        self.label_11.setGeometry(QtCore.QRect(260, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(perceptron)
        self.label_12.setGeometry(QtCore.QRect(500, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.checkBox = QtWidgets.QCheckBox(perceptron)
        self.checkBox.setGeometry(QtCore.QRect(240, 130, 201, 25))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(perceptron)
        self.checkBox_2.setGeometry(QtCore.QRect(490, 130, 151, 25))
        self.checkBox_2.setObjectName("checkBox_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(perceptron)
        self.textBrowser_2.setGeometry(QtCore.QRect(760, 20, 451, 301))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_5 = QtWidgets.QPushButton(perceptron)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 270, 151, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(perceptron)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 330, 151, 51))
        self.pushButton_6.setStyleSheet("background-color: rgb(224, 234, 255);")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(perceptron)
        QtCore.QMetaObject.connectSlotsByName(perceptron)

    def retranslateUi(self, perceptron):
        _translate = QtCore.QCoreApplication.translate
        perceptron.setWindowTitle(_translate("perceptron", "Interfaz para Red Neuronal"))
        self.label_6.setText(_translate("perceptron", "Pyceptron v1.2 © 2018 Darío E. Farías <defarias@gmail.com>  Licencia Pública General (GPL) v3"))
        self.label_2.setText(_translate("perceptron", "COLOR"))
        self.label.setText(_translate("perceptron", "Información del Color Seleccionado"))
        self.label_3.setText(_translate("perceptron", "Rojo: 0"))
        self.pushButton.setText(_translate("perceptron", "Verificar Neurona"))
        self.label_5.setText(_translate("perceptron", "Azul: 0"))
        self.label_4.setText(_translate("perceptron", "Verde: 0"))
        self.pushButton_2.setText(_translate("perceptron", "Entrenar Neurona"))
        self.pushButton_3.setText(_translate("perceptron", "Color Permitido"))
        self.pushButton_4.setText(_translate("perceptron", "Color Denegado"))
        self.label_10.setText(_translate("perceptron", "PyCeptron"))
        self.label_11.setText(_translate("perceptron", "Perceptron4test"))
        self.label_12.setText(_translate("perceptron", "Edu-CIAA"))
        self.checkBox.setText(_translate("perceptron", "Habilitar Perceptron4test.c"))
        self.checkBox_2.setText(_translate("perceptron", "Habilitar Edu-CIAA"))
        self.pushButton_5.setText(_translate("perceptron", "Datos Entrenamiento"))
        self.pushButton_6.setText(_translate("perceptron", "Nuevo Entrenamiento"))

